# SPDX-License-Identifier: GPL-2.0-only
# OCSFS v2 out-of-tree kernel module build rules.
#   make -C /lib/modules/$(uname -r)/build M=$PWD/kmod2 modules

obj-m += ocsfs2.o

ocsfs2-y := super.o inode.o bitmap.o dir.o rename.o iomap.o journal.o \
	    refcount.o reflink.o file.o xattr.o extent_btree.o \
	    cluster.o lease.o grow.o transport/scsi_pr.o

ccflags-y := -I$(src) -Wall
