# OCSFS — Open Cluster Shared FileSystem
# Kernel module build rules
# SPDX-License-Identifier: GPL-2.0-only

obj-m += ocsfs.o

ocsfs-y := super.o inode.o dir.o dir_rename.o dir_btree.o file.o \
           extent.o extent_btree.o journal.o journal_replay.o bitmap.o \
           scsi_pr.o xattr.o acl.o cas.o lock.o lock_io.o heartbeat.o node.o recovery.o \
           iomap.o alloc.o thin.o \
           snapshot.o refcount.o compress.o compress_file.o \
           btree.o btree_mod.o \
           test_lock.o test_cas.o
