# OCSFS — Open Cluster Shared FileSystem
# Kernel module build rules
# SPDX-License-Identifier: GPL-2.0-only

obj-m += ocsfs.o

ocsfs-y := super.o inode.o dir.o file.o extent.o journal.o bitmap.o \
           scsi_pr.o lock.o heartbeat.o node.o recovery.o \
           iomap.o alloc.o thin.o \
           snapshot.o refcount.o compress.o \
           test_lock.o
